export const enum EnvKey {
  NODE_ENV = 'NODE_ENV',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_USERNAME = 'REDIS_USERNAME',
  REDIS_PASSWORD = 'REDIS_PASSWORD',

  DATASOURCE_MARGIET_URI = 'DATASOURCE_MARGIET_URI',
  DATASOURCE_MARGIET_DBNAME = 'DATASOURCE_MARGIET_DBNAME',

  G_CLIENT_ID = 'G_CLIENT_ID',
  G_CLIENT_SECREC = 'G_CLIENT_SECREC',
  G_REDIRECT_URI = 'G_REDIRECT_URI',
  G_REFRESH_TOKEN = 'G_REFRESH_TOKEN',
  G_FOLDER_ID = 'G_FOLDER_ID',

  SERVER_HOST = 'SERVER_HOST',
  SERVER_PORT = 'SERVER_PORT',
  SERVER_PREFIX = 'SERVER_PREFIX',

  SAVE_STRATEGIES = 'SAVE_STRATEGIES',

  MINIO_ENDPOINT = 'MINIO_ENDPOINT',
  MINIO_PORT = 'MINIO_PORT',
  MINIO_USE_SSL = 'MINIO_USE_SSL',
  MINIO_ACCESS_KEY = 'MINIO_ACCESS_KEY',
  MINIO_SECRET_KEY = 'MINIO_SECRET_KEY',
  MINIO_BUCKET= 'MINIO_BUCKET'
}
