export const enum EnvKey {
  NODE_ENV = 'NODE_ENV',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_USERNAME = 'REDIS_USERNAME',
  REDIS_PASSWORD = 'REDIS_PASSWORD',

  DATASOURCE_MARGIET_URI = 'DATASOURCE_MARGIET_URI',
  DATASOURCE_MARGIET_USERNAME = 'DATASOURCE_MARGIET_USERNAME',
  DATASOURCE_MARGIET_PWD = 'DATASOURCE_MARGIET_PWD',
  DATASOURCE_MARGIET_DBNAME = 'DATASOURCE_MARGIET_DBNAME',
  DATASOURCE_MARGIET_HOST = 'DATASOURCE_MARGIET_HOST',
  DATASOURCE_MARGIET_PORT = 'DATASOURCE_MARGIET_PORT',
}
